[package]
name = "limbo_sui"
version = "0.2.0"
edition = "2021"
authors = ["Astrophel"]
description = "Your Move contract won't leave the same."

[[bin]]
name = "limbo_sui"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
colored = "2"
indicatif = { version = "0.17", features = ["tokio"] }
chrono = "0.4"
regex = "1"
git2 = "0.19"
anyhow = "1"
dotenv = "0.15"
walkdir = "2"

[profile.release]
opt-level = 3
strip = true
